version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: flashcard-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flashuser
      POSTGRES_PASSWORD: flashpass
      POSTGRES_DB: flashcard_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: