apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-blue
  template:
    metadata:
      labels:
        app: backend-blue
    spec:
      containers:
        - name: backend
          image: backend-blue:v1
          ports:
            - containerPort: 8000