apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-green
  template:
    metadata:
      labels:
        app: frontend-green
    spec:
      containers:
        - name: frontend
          image: frontend-green:v1
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE
              value: http://backend-green:8000