replicaCount: 1

image:
  repository: gcr.io/flashcard-project-2025/nextjs-app
  tag: v1.0.2
  pullPolicy: IfNotPresent

containerPort: 3000

buildArgs:
  NEXT_PUBLIC_API_BASE_URL: "https://api.34-22-91-115.nip.io"

env:
  ENV: "prod"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-http
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: next.34-22-91-115.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - next.34-22-91-115.nip.io
      secretName: next-tls-secret