apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: ENV
              value: {{ .Values.env.ENV | quote }}
            - name: FRONTEND_ORIGIN
              value: {{ .Values.env.FRONTEND_ORIGIN | quote }}

            - name: POSTGRES_HOST
              value: {{ .Values.env.POSTGRES_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.env.POSTGRES_PORT | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB | quote }}
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}

            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}

            - name: SECRET_KEY
              value: {{ .Values.env.SECRET_KEY | quote }}
            - name: ACCESS_TOKEN_ALGORITHM
              value: {{ .Values.env.ACCESS_TOKEN_ALGORITHM | quote }}
            - name: REFRESH_TOKEN_ALGORITHM
              value: {{ .Values.env.REFRESH_TOKEN_ALGORITHM | quote }}
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: {{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}