name: Trigger GCP Cloud Build

on:
  push:
    branches: [ dev ]

jobs:
  trigger-cloudbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: flashcard-project-2025
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Activate service account
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          ACCOUNT=$(gcloud config list account --format="value(core.account)")
          gcloud config set account "$ACCOUNT"

      - name: Trigger Cloud Build
        run: |
          COMMIT_MSG=$(git show -s --format=%B $GITHUB_SHA)
          echo "📍 COMMIT_MSG: $COMMIT_MSG"
          SHORT_SHA=$(git rev-parse --short $GITHUB_SHA 2>/dev/null || echo "manual-$(date +%s)")
          echo "📍 SHORT_SHA: $SHORT_SHA"
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --no-stream \
            --substitutions=_CLUSTER_NAME="flashcard-cluster",_CLUSTER_REGION="asia-northeast3-a",_PROJECT_ID="flashcard-project-2025",_FE_CHART_PATH="flashcard-frontend/charts/nextjs",_BE_CHART_PATH="flashcard-backend/charts/fastapi",_COMMIT_MSG="${COMMIT_MSG}",_SHORT_SHA="${SHORT_SHA}" \
            .